namespace HRM_Project.Exceptions
{
    public class ToErrors
    {
        public const string INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
        public const string ENTITY_WITH_THIS_ID_NOT_FOUND = "ENTITY_WITH_THIS_ID_NOT_FOUND";
        public const string ENTITY_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "ENTITY_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string ENTITY_WITH_THIS_ID_NOT_FOUND_FOR_DELETE = "ENTITY_WITH_THIS_ID_NOT_FOUND_FOR_DELETE";
        public const string THIS_USERNAME_ALREADY_EXIST = "THIS_USERNAME_ALREADY_EXIST";
        public const string COMPANY_WITH_THIS_ID_NOT_FOUND = "COMPANY_WITH_THIS_ID_NOT_FOUND";
        public const string CITY_HAS_REFFERENCE_TO_COMPANY = "CITY_HAS_REFFERENCE_TO_COMPANY";
        public const string CITY_WITH_THIS_ID_NOT_FOUND = "CITY_WITH_THIS_ID_NOT_FOUND";
        public const string REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND";
        public const string EXPIRED_REFRESH_TOKEN = "EXPIRED_REFRESH_TOKEN";
        public const string USER_NOT_FOUND = "USER_NOT_FOUND";
        public const string COMPANY_HAS_REFFERENCE_DEPARTMENTS = "COMPANY_HAS_REFFERENCE_DEPARTMENTS";
        public const string ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
        public const string ENTITY_WITH_THIS_NAME_ALREADY_EXIST = "ENTITY_WITH_THIS_NAME_ALREADY_EXIST";
        public const string ENTITY_ALREADY_USED = "ENTITY_ALREADY_USED";
        public const string FILE_IS_EMPTY = "FILE_IS_EMPTY";
        public const string ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND";
        public const string ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND";
        public const string THIS_ORGANIZATION_USED_ANOTHER_OBJECT = "THIS_ORGANIZATION_USED_ANOTHER_OBJECT";
        public const string DEPARTMENT_WITH_THIS_ID_NOT_FOUND = "DEPARTMENT_WITH_THIS_ID_NOT_FOUND";
        public const string DEPARTMENT_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "DEPARTMENT_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string DEPARTMENT_WITH_THIS_ID_NOT_FOUND_FOR_DELETE = "DEPARTMENT_WITH_THIS_ID_NOT_FOUND_FOR_DELETE";
        public const string DEPARTMENT_HAS_REFERENCES_DIVISIONS = "DEPARTMENT_HAS_REFERENCES_DIVISIONS";
        public const string DIVISION_WITH_THIS_ID_NOT_FOUND = "DIVISION_WITH_THIS_ID_NOT_FOUND";
        public const string EMPLOYEE_WITH_THIS_ID_NOT_FOUND = "EMPLOYEE_WITH_THIS_ID_NOT_FOUND";
        public const string EMPLOYEE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "EMPLOYEE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string EMPLOYEE_WITH_THIS_ID_NOT_FOUND_FOR_DELETE = "EMPLOYEE_WITH_THIS_ID_NOT_FOUND_FOR_DELETE";
        public const string POSITION_WITH_THIS_ID_NOT_FOUND = "POSITION_WITH_THIS_ID_NOT_FOUND";
        public const string USER_WITH_THIS_ID_NOT_FOUND = "USER_WITH_THIS_ID_NOT_FOUND";
        public const string ORDERTYPE_WITH_THIS_ID_NOT_FOUND = "ORDERTYPE_WITH_THIS_ID_NOT_FOUND";
        public const string NEWS_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "NEWS_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string NEWS_WITH_THIS_ID_NOT_FOUND = "NEWS_WITH_THIS_ID_NOT_FOUND";
        public const string ACT_WITH_THIS_ID_NOT_FOUND = "ACT_WITH_THIS_ID_NOT_FOUND";
        public const string ACT_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "ACT_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string ACTTYPE_WITH_THIS_ID_NOT_FOUND = "ACTTYPE_WITH_THIS_ID_NOT_FOUND";
        public const string ACTTYPE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "ACTTYPE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string APPLICATION_WITH_THIS_ID_NOT_FOUND = "APPLICATION_WITH_THIS_ID_NOT_FOUND";
        public const string APPLICATION_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "APPLICATION_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string APPLICATIONTYPE_WITH_THIS_ID_NOT_FOUND = "APPLICATIONTYPE_WITH_THIS_ID_NOT_FOUND";
        public const string APPLICATIONTYPE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE = "APPLICATIONTYPE_WITH_THIS_ID_NOT_FOUND_FOR_UPDATE";
        public const string VACANCY_WITH_THIS_ID_NOT_FOUND = "VACANCY_WITH_THIS_ID_NOT_FOUND";
        public const string REFERENCE_WITH_THIS_ID_NOT_FOUND = "REFERENCE_WITH_THIS_ID_NOT_FOUND";
        public const string REFERENCETYPE_WITH_THIS_ID_NOT_FOUND = "REFERENCETYPE_WITH_THIS_ID_NOT_FOUND";
        public const string TIMESHEET_WITH_THIS_ID_NOT_FOUND = "TIMESHEET_WITH_THIS_ID_NOT_FOUND";
        public const string TIMESHEETTYPE_WITH_THIS_ID_NOT_FOUND = "TIMESHEETTYPE_WITH_THIS_ID_NOT_FOUND";
    }
}
